# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[aws]
disabled = true

[[battery.display]]
threshold = 20
style = "red bold"
